Fix: Adapt to changes in PEtab test suite API
Fix test.test_petab_suite:test_petab_suite.py:35 load_solution() missing 1 required positional argument: 'format'

Closes #507